# Generated by Django 5.2.8 on 2025-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New Construction'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_renovation', 'Needs Renovation'), ('demolition', 'Demolition Required')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Property description'),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_rating',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, help_text='Floor number (for apartments)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, help_text='Property has balcony'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(blank=True, help_text='Building has elevator', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_terrace',
            field=models.BooleanField(default=False, help_text='Property has terrace'),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time data was synced from source', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.IntegerField(default=0, help_text='Number of parking spaces'),
        ),
        migrations.AddField(
            model_name='property',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL to original listing', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, help_text='Total floors in building', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, help_text='Year the property was built', null=True),
        ),
    ]
