# Generated by Django 5.2.8 on 2025-12-04 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_contactrequest_feedback_portfolio_supportmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["property", "contacted"], name="api_contact_propert_def14f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["user", "created_at"], name="api_contact_user_id_11a283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["user", "is_default"], name="api_portfol_user_id_c4356c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["user", "created_at"], name="api_portfol_user_id_ddf489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioproperty",
            index=models.Index(
                fields=["portfolio", "added_at"], name="api_portfol_portfol_2a0d19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "listing_status"], name="api_propert_propert_bacda8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price", "size_sqm"], name="api_propert_price_7fc62b_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["region", "property_type"], name="api_propert_region__363630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["listing_status", "created_at"], name="api_propert_listing_2e155b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["bedrooms", "bathrooms"], name="api_propert_bedroom_40e181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedproperty",
            index=models.Index(
                fields=["user", "created_at"], name="api_savedpr_user_id_5f5452_idx"
            ),
        ),
    ]
