# Generated by Django 5.2.8 on 2025-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_property_geographic_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autonomousregion',
            new_name='api_autonom_code_c32ef8_idx',
            old_name='api_autonom_code_idx',
        ),
        migrations.RenameIndex(
            model_name='autonomousregion',
            new_name='api_autonom_name_2f40be_idx',
            old_name='api_autonom_name_idx',
        ),
        migrations.RenameIndex(
            model_name='district',
            new_name='api_distric_code_cca079_idx',
            old_name='api_distric_code_idx',
        ),
        migrations.RenameIndex(
            model_name='district',
            new_name='api_distric_name_138fa4_idx',
            old_name='api_distric_name_idx',
        ),
        migrations.RenameIndex(
            model_name='municipality',
            new_name='api_municip_code_a29959_idx',
            old_name='api_municip_code_idx',
        ),
        migrations.RenameIndex(
            model_name='municipality',
            new_name='api_municip_name_80928c_idx',
            old_name='api_municip_name_idx',
        ),
        migrations.RenameIndex(
            model_name='municipality',
            new_name='api_municip_distric_dcb0ed_idx',
            old_name='api_municip_distric_idx',
        ),
        migrations.RenameIndex(
            model_name='municipality',
            new_name='api_municip_autonom_38653f_idx',
            old_name='api_municip_autonom_idx',
        ),
        migrations.RenameIndex(
            model_name='parish',
            new_name='api_parish_code_a8a578_idx',
            old_name='api_parish_code_idx',
        ),
        migrations.RenameIndex(
            model_name='parish',
            new_name='api_parish_name_5e2a74_idx',
            old_name='api_parish_name_idx',
        ),
        migrations.RenameIndex(
            model_name='parish',
            new_name='api_parish_municip_88710c_idx',
            old_name='api_parish_municip_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='api_propert_distric_f761fb_idx',
            old_name='api_propert_distric_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='api_propert_municip_8e41d4_idx',
            old_name='api_propert_municip_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='api_propert_parish__96a92c_idx',
            old_name='api_propert_parish_idx',
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district', 'municipality', 'parish'], name='api_propert_distric_b6d182_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'condition', 'energy_rating'], name='api_propert_propert_ab9730_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['external_id'], name='api_propert_externa_5ee589_idx'),
        ),
    ]
